### ISSUE TITLE
Upgrade to .NET Core 3

### ISSUE THREAD

**Issue by ghost** [ThoNohT/NohBoard#103]
As .NET Core gets closer to GA I think support for it should be explored since it provides cross platform support and performance boosts. Not to mention that migration will be necessary when .NET 5 is released.

In moving I found these resources useful:
- https://github.com/hvanbakel/CsprojToVs2017
- https://devblogs.microsoft.com/dotnet/how-to-port-desktop-applications-to-net-core-3-0/
- https://docs.microsoft.com/en-us/dotnet/core/porting/winforms

**Comment by ThoNohT** [comment]
Interesting idea. Cross-platform won't be as easy since winforms is still
only supported on Windows. Also I'm not entirely sure how well low level kb
hooks work in Core, as this is the main thing that didn't work on Linux
with mono before.

But it's definitely worth giving it a try.

**Comment by rogersachan** [comment]
.NET 5 is supposed to let you drop in the mono compiler and so on, so regardless of when this is implemented it's future proofing for the .NET 5 release

**Comment by ThoNohT** [comment]
Working on this at the moment in this branch: https://github.com/ThoNohT/NohBoard/tree/dotnetcore

It will still be Windows only, but the hooking, and windows forms in .net-core all seems to be working well. I just need to get proper publishing setup, and see what the new requirements are for people who want to run the program. (I don't want to bundle the entire core framework with it, that makes the executable immensely bigger.)

**Comment by ThoNohT** [comment]
First build on .net core 3.1 passing CI: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/32759884/artifacts

@joao7yt Would you mind trying to run this? I am wondering if this will now require some additional framework.

**Comment by joao7yt** [comment]
so, the selfcontained one runs ok, the other one says:
![image](https://user-images.githubusercontent.com/10665193/81489976-6b191180-9252-11ea-851d-993aba606754.png)

**Comment by ThoNohT** [comment]
It seems that this is the required runtime to run the not self-contained one: https://dotnet.microsoft.com/download/dotnet-core/current/runtime (So the current one, or anything later is probably already fine in the future.)

I tested this with my laptop by uninstalling and deleting everything related to .net until I couldn't get it to start and then installing this. @joao7yt are you able to confirm that the small one can be run if you install this runtime?

It would be best if I can release the small one, since the file goes from ~1MB to ~150MB if I have to bundle the required .net-core libraries. That's a huge change since .net framework, where this bundling was basically not possible, and the framework was distributed with Windows.

**Comment by joao7yt** [comment]
confirming. I can run the not selfcontained if installing the runtime 3.1.3

**Comment by ThoNohT** [comment]
Thanks a lot for testing!

So now that the viability of running NohBoard on .net-core is confirmed, I think I will continue developing further features and bugfixes in .net-core.  I'll probably also spend some time refactoring stuff and bringing the code up to date with the latest language features.

There won't be a release right now, since just the framework shift doesn't add any value to the users. But I will consider this feature as closed.
