### ISSUE TITLE
Importing images into global isn't working

### ISSUE THREAD

**Issue by RubyPiec** [ThoNohT/NohBoard#125]
Okay, so the title of this is really misleading, I'm just talking about joao7yt, I really like the normal-black_normal-white.style and would like it to be global, same for the images, however I ran into a problem and some textures look really weird if I do so, I don't know if this is a bug or not, and I would like an answer on how to fix it.

**Comment by joao7yt** [comment]
I think it's not possible... but you just need to "save as" your definition (lets say the category is "test_category" and name is "test_name"), copy the "images" folder from my "joao7yt" folder to your "test_category" folder and copy the "black_normal-white.style" from my "fps" folder to your "test_name" folder.

**Comment by RubyPiec** [comment]
Well, it's mainly just me trying to get an entire keyboard with the joao7yt, aka using the "Normal" one

**Comment by joao7yt** [comment]
Oooh I think I get it now... You could do it but some keys look weird... I think you are referring to keys like Shift, Space, Tab... those keys need to be configured manually because they use specific images to them... You can open the images folder and take a look at the specific ones, you will get it

**Comment by RubyPiec** [comment]
Thanks!
