### ISSUE TITLE
Crash on running .exe for Streamlabs

### ISSUE THREAD

**Issue by craigscheesecake** [ThoNohT/NohBoard#126]
I'm trying to implement a keyboard overlay for my stream but the .exe file keeps crashing when I try to install.

NohBoard crashed. Exception message: Could not load file or assembly 'NohBoard.Hooking, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

And then it shows where it put the crash log. Is there a fix to this? 

Thanks!

**Comment by ThoNohT** [comment]
This is most likely due to your antivirus marking the Hooking library (NohBoard.Hooking.dll) as a keylogger (since that's essentially what it does). You'll have to add an exception to the antivirus you are using for NohBoard.

That, or you didn't copy or extract that dll file with the rest of NohBoard.
Anyway, this is not a bug with NohBoard.

**Comment by craigscheesecake** [comment]
Thank you so much!
