### ISSUE TITLE
Cycling through  elements under cursor when making selections

### ISSUE THREAD

**Issue by LotBlind** [ThoNohT/NohBoard#53]
When two keys overlap each other, even though the one I wanted to edit was highlighted during mouse-hovering, right-clicking gives me the other key's options (the first one I had placed) until I click somewhere where they don't overlap.

Relatedly, if two keys overlap perfectly, you can't seemingly select the other one at all, unless you use "move to top" on the one it's selecting, at which point the new bottom one can be chosen. This suggests that the problem is hovering highlights the top one, but the bottom one will be selected.

**Comment by ThoNohT** [comment]
I made the selected element sticky like that, because it would otherwise be impossible to drag or resize a button that is below another one. Therefore, you have to cancel the current selection in order to make a new one.

From my testing, it always selects the topmost one. I thought I had implemented a way to cycle through the keys at the cursor location. But I can't actually get it to work. So that might be a thing to implement in a later version. For now, you'll probably just have to move them away from each other and move them back on top of each other once you're done editing them.

**Comment by ThoNohT** [comment]
Implemented in v1.2.0
