### ISSUE TITLE
Crash related to Windows snapping feature in dual monitor setup

### ISSUE THREAD

**Issue by monagii** [ThoNohT/NohBoard#88]
In a dual monitor setup, whenever any window crosses the monitor threshold and the Windows snapping feature activates, NohBoard crashes. 
![image](https://user-images.githubusercontent.com/45644941/49555686-eb994d00-f8bd-11e8-9fa7-75a03387fbad.png)

It will also sometimes crash when simply moving the cursor back and forth between monitors. A wild guess, but it may be related to the monitors running at different refresh rates.

Monitor details:
Left = Acer XB270HU, 144hz 2560x1440
Right = Dell S2718D, 60hz 2560x1440

I've attached the related event log entries.

I've disabled the feature here for the time being to reduce the crashes
![image](https://user-images.githubusercontent.com/45644941/49555345-c6580f00-f8bc-11e8-86a1-448699fac113.png)

[nohboard_crash.zip](https://github.com/ThoNohT/NohBoard/files/2651318/nohboard_crash.zip)

**Comment by ThoNohT** [comment]
This should give me a good hint:


`Application:  NohBoard.exe Framework Version: v4.0.30319 Description: The process was  terminated due to an unhandled exception. Exception Info:  System.InvalidOperationException at  System.Linq.Enumerable.SingleOrDefault[[System.Nullable'1[[System.Drawing.Point,  System.Drawing, Version=4.0.0.0, Culture=neutral,  PublicKeyToken=b03f5f7f11d50a3a]], mscorlib, Version=4.0.0.0, Culture=neutral,  PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable'1<System.Nullable'1<System.Drawing.Point>>)  at  ThoNohT.NohBoard.Hooking.MouseState.GetScreenCenterForPoint(System.Drawing.Point)  at ThoNohT.NohBoard.Hooking.MouseState.RegisterLocation(System.Drawing.Point,  Int32) at ThoNohT.NohBoard.Hooking.Interop.HookManager.MouseHookProc(Int32,  Int32, IntPtr)`

**Comment by Butt4cak3** [comment]
Sorry, took me a while to get back to this.

I couldn't reproduce this crash. There seems to be something else contributing to it. This is my setup:

Left: Asus ROG Strix XG32V, 2560x1440 @144Hz
Right: Some older Acer, 1680x1050 @60Hz
OS: Windows 10

**Comment by ThoNohT** [comment]
4d76d46 should solve this.

**Comment by monagii** [comment]
@ThoNohT Seems solid after brief initial testing - https://i.imgur.com/ayR7ru6.gifv

Well done!
