### ISSUE TITLE
Nohboard Issue with Logitech Mouse

### ISSUE THREAD

**Issue by snizzy** [ThoNohT/NohBoard#96]
Nohboard creates a lag for my mouse in game. Its very frustrating. It doesn't happen with my stock mouse but it happens with my Logitech G502 and my friend's G602. Can someone please help me out?

**Comment by joao7yt** [comment]
Any game? Happens in full screen only or windowed as well? Can you test if your mouse causes in game lag in a machine that runs NohBoard flawlessly?

The details can help us helping you.

**Comment by snizzy** [comment]
Okay so my friend tried it with his PC and we have same mouse works perfectly fine. The issue is in both windowed and borderless modes. And it happens with any game the second I load into a match. In lobbies its fine, everywhere else it works fine, the second I drop into a match the mouse "skips" or lags. I have an i7 and a gtx 2080. The second I close nohboard, I get full control of my mouse.  Any ideas what it could be.

**Comment by joao7yt** [comment]
Wait, your friend doesn’t have the issue testing with the same mouse, right? If so, must be some software you are running in your machine.

If you are using the logitech software, try to exit the software and test again... basically try exit any other softwares that can be hooking mouse events

I say this because i know razer software does hook mouse events in order to show you device statistics... idk if logitech does the same

Idk if your already tested, but try testing not running the software you use to capture your screen, like obs studio, just test nohboard and your game

If you have multiple monitors, try testing with only one (shouldn’t matter but i know multiple monitors has caused issues in the past)

Try messing with nohboard and your game’s priorities in task manager.

Run nohboard and your game as adm

I think that’s all i could possibly think of you can test out

**Comment by ThoNohT** [comment]
Closing since it's more than a year old without new information.
